CREATE TABLE IF NOT EXISTS usuarios (
 id SERIAL PRIMARY KEY, usuario VARCHAR(50) UNIQUE NOT NULL,
 password VARCHAR(255) NOT NULL, fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS proveedores (
 id SERIAL PRIMARY KEY, nombre VARCHAR(100) NOT NULL, correo VARCHAR(120) NOT NULL,
 telefono VARCHAR(20) NOT NULL, producto VARCHAR(150) NOT NULL
);
CREATE TABLE IF NOT EXISTS productos (
 id SERIAL PRIMARY KEY, nombre VARCHAR(150) NOT NULL, categoria VARCHAR(40) NOT NULL,
 descripcion TEXT NOT NULL, talla VARCHAR(10) NOT NULL,
 precio NUMERIC(12,2) NOT NULL CHECK(precio > 0), estado VARCHAR(30) NOT NULL,
 imagen VARCHAR(100) NOT NULL DEFAULT 'ropa.jpg',
 proveedor_id INTEGER NOT NULL REFERENCES proveedores(id) ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS clientes (
 id SERIAL PRIMARY KEY, nombre VARCHAR(100) NOT NULL, correo VARCHAR(120) NOT NULL,
 telefono VARCHAR(20) NOT NULL, direccion VARCHAR(200) NOT NULL
);
CREATE TABLE IF NOT EXISTS facturacion (
 id SERIAL PRIMARY KEY, cliente_id INTEGER NOT NULL REFERENCES clientes(id) ON DELETE RESTRICT,
 producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
 cantidad INTEGER NOT NULL CHECK(cantidad BETWEEN 1 AND 100000),
 precio_unitario NUMERIC(12,2) NOT NULL CHECK(precio_unitario > 0),
 total NUMERIC(18,2) NOT NULL CHECK(total = cantidad * precio_unitario),
 fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS mensajes (
 id SERIAL PRIMARY KEY, nombre VARCHAR(100) NOT NULL, correo VARCHAR(120) NOT NULL,
 mensaje VARCHAR(2000) NOT NULL, fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_producto_proveedor ON productos(proveedor_id);
CREATE INDEX IF NOT EXISTS idx_factura_cliente ON facturacion(cliente_id);
CREATE INDEX IF NOT EXISTS idx_factura_producto ON facturacion(producto_id);

CREATE TABLE IF NOT EXISTS ventas (
 id SERIAL PRIMARY KEY,
 cliente_id INTEGER NOT NULL REFERENCES clientes(id) ON DELETE RESTRICT,
 usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
 token VARCHAR(64) UNIQUE NOT NULL,
 total NUMERIC(18,2) NOT NULL CHECK(total > 0),
 fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE facturacion ADD COLUMN IF NOT EXISTS venta_id INTEGER REFERENCES ventas(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_facturacion_venta ON facturacion(venta_id);

ALTER TABLE productos ADD COLUMN IF NOT EXISTS fuente_url TEXT NOT NULL DEFAULT '';
